stages:
  - test
  - build
  - deploy

### TEMPLATES ###
.build:
  stage: build
  image: node:14.15-buster
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_ENVIRONMENT_NAME
  script:
    - yarn && yarn build --environment=${ENVIRONMENT}
    - STORYBOOK_ENV=${ENVIRONMENT} yarn build-storybook
    - mv storybook-static build
  cache:
    paths:
      - node_modules/
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG-$CI_ENVIRONMENT_NAME"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG-$CI_ENVIRONMENT_NAME"
    paths:
      - build
    expire_in: 1 hour
  tags:
    - aws-runner

test:
  stage: test
  image: node:14.15-buster
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_ENVIRONMENT_NAME
  script:
    - yarn && yarn test --coverage
  cache:
    paths:
      - node_modules/
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  artifacts:
    paths:
      - coverage
  tags:
    - aws-runner
  only:
    - merge_requests

.deploy:
  stage: deploy
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_ENVIRONMENT_NAME
  # https://gitlab.com/gitlab-org/cloud-deploy/-/tags/v0.3.3
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base@sha256:654cb6d3ba01f9753a4a3f20d6c39fb0b9c111d080bb6f90606cec284b4be7e9
  script:
    - aws --version
    - aws s3 sync --delete build/ s3://$BUCKET
  tags:
    - aws-runner

### END OF TEMPLATES ###

### PROD ENVIRONMENT ###
build_production:
  extends: .build
  environment: production
  variables:
    ENVIRONMENT: production
  only:
    - master

    
deploy_production:
  stage: deploy
  extends: .deploy
  environment: production
  variables:
    AWS_ACCESS_KEY_ID: $PROD_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $PROD_AWS_SECRET_ACCESS_KEY
    BUCKET: $PROD_BUCKET
    ENVIRONMENT: production
  only:
    - master
  dependencies:
    - build_production
### END OF PROD ENVIRONMENT ###


### DEMO ENVIRONMENT ###
build_demo:
  extends: .build
  environment: demo
  variables:
    ENVIRONMENT: sandbox
  only:
    - master

deploy_demo:
  stage: deploy
  extends: .deploy
  environment: demo
  variables:
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
    BUCKET: $DEMO_BUCKET
  only:
    - master
  dependencies:
    - build_demo
### END OF DEMO ENVIRONMENT ###


### STAGING ENVIRONMENT ###
build_staging:
  extends: .build
  environment: staging
  variables:
    ENVIRONMENT: staging
  before_script:
    - apt-get update && apt-get install -yq gettext-base
    - envsubst < ./config/environments/staging.tpl.js > ./config/environments/staging.js
  only:
    - stage


deploy_staging:
  extends: .deploy
  environment: staging
  variables:
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
    BUCKET: $STAGING_BUCKET
  only:
    - stage
  dependencies:
    - build_staging
### END OF STAGING ENVIRONMENT ###
