name: Prepare feature package
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@cleeng'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "pkaczmarek@cleeng.com"
      - run: npm ci
      - run: |
            echo "PACKAGE_VERSION=$(cat package.json | grep -o  '"version": "[^"]*' | grep -o '[^"]*$')" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm version ${{ env.PACKAGE_VERSION}}-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}
      - run: npm run compile
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
